version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    secrets:
      - db_password

  apache:
    image: httpd:2.4
    ports:
      - "80:80"
    volumes:
      - ./public_html:/usr/local/apache2/htdocs/

secrets:
  db_password:
    file: ./db/password.txt

volumes:
  db_data:
